name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/masterdnsvpn
          tags: |
            # version from tag (v1.2.3 -> 1.2.3)
            type=semver,pattern={{version}}
            # full tag (v1.2.3)
            type=ref,event=tag
            # latest only on default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
